services:
  groceries:
    image: ghcr.io/tomekbielaszewski/groceries:latest
    container_name: groceries
    ports:
      - "8080:8080"
    volumes:
      - ./groceries:/data
    restart: unless-stopped
